POST http://localhost:3003/create/user
Content-Type: application/json

{
  "name": "vito22122",
  "email": "viuu222@usuario.com",
  "age": 12
}

###

POST http://localhost:3003/create/product
Content-Type: application/json

{
  "name": "boné",
  "description": "boné rosa com fecho lateral",
  "price": 25.80
}

###

GET http://localhost:3003/users
Content-Type: application/json

